### ISSUE TITLE
./hashcat used but not found in the project

### ISSUE THREAD

**Issue by KOSSOKO** [floyd-fuh/JKS-private-key-cracker-hashcat#2]
Hello,
Thanks for this project. In the cocumentation, you use the commande 
`./hashcat -m 15500 -a 3 -1 '?u|' -w 3 hash.txt ?1?1?1?1?1?1?1?1?1` but I can't find ./hashcat in the project.

Please could you tell me where i can find it ?
Big thanks.

**Comment by roycewilliams** [comment]
Stable binaries: https://hashcat.net/hashcat/
Beta: https://hashcat.net/beta/
Source: https://github.com/hashcat/hashcat

Also requires CUDA or OpenCL - use the latest stable of these from your GPU architecture manufacturer (NVIDIA or AMD)

**Comment by KOSSOKO** [comment]
Thanks a lot for this very rapid answer.
