### ISSUE TITLE
Keystore file hashes not loaded

### ISSUE THREAD

**Issue by KOSSOKO** [floyd-fuh/JKS-private-key-cracker-hashcat#3]
Hello, I follow all the instruction.
I generate my hash.txt and got 
`java -jar JksPrivkPrepare.jar ../rdvpref-release.keystore > hash.txt`
`Alias: rdvpref, algorithm: RSA, keysize or field size: 2048`
cat hash.txt 
`$jksprivk$*E59A72E284EA44B01EBC7D36825E125CCB670EBC*1BA4003CD038051113EAE7EAA21539298CCB72AD*D1A471FDF7ECC4ABBA73E374C8A85468E2D0FA3D95634F1617F8BF6145B572B76916D9C6DB8C4CFAB65939E34AA2CD9952B672A882B60236EC39EFD07D60E79C5635BD4CD7206E8A57D26963D42F1089DF72B3CE1F6DDE324417EB330BB281E247219AAC00E787C56843984118822F1784BC71FA7BF6F38B34F8A076D1ACA2658D77CC584AD95881350659B7A215BC717A39A222349E6553245665816939CEAE5D62CF2932C52B64D1B806D02A0A53A0DD0AC12A0F0A34207C79B68C5EB9629E8B362E54E16397E1D3F20C32E20886F074A370184EA9159A20600A674231B71CD627B88B5B1A4B6A3705361181026EA5D3CD0E37A72F25FD34C666000191485518C78FEDA4A49A0BAD49F6FCEB3DCE4FB19A7A8F5C6581DDBA38B97F09FE752D655C2752C0FB95CC3EBC92AC65EB2E7481C26BC3186816C76F55F73785C654BBFCA840BD6965D9D7F8AFEE4D140C4963A4647F5AE40EA4A6C3374940989112D761155F2C81AB79850C440F941CF008408F978CEC415DD95F42617F8EAD3FF09DBD52C447E23FD8CE1FA5EB4590D52BECF806DA5D666EA10B6DBDD4EC994282BF54293C10531E426439478C673CEEA0611B438E236C3E19264D56300161F47590A9577F2BB7CDA8600D58DF348FF90C15C00A7F28D37AFB69F680F45023A767C2D94DAE69BC1D7969E5FEE98CDF1309D3F66F53C9DAA0EFBDD70B660610D3A73CF855EA2CC1CFC69CFB29A03B6B184CAA616E3BC4E52E94F96DA9FB9ADF2B472522A7F61E995DB1950260F9C4B0AB80536D9B08C4963AB7EAEA7CD46CDA76E408BE9A504B45266D4118A5EFB1E144A530C71778CA8F2AEC872250700903A1536C4B1951DE0E7148A22FFE4D38B65EC051F3452AB54FFB132F06F0BEB7647C5090EE03EE39EF69E0C33512A51AC7002ACE7528A2EB451DF477EFD99631CB1000D9856D1401A684B0D7BC0F4B95F0B968B877A5390139BC31D6E6B06ABC9E6666A374472ACC5AA519CF823D5126E534FF38D7DF600F3142590E8743F7569F20955008CC86F747D43D26483EB593BCADD1B975A18464DC1F960BA9F144A5E6C88B7D2090D44C0DB12C6B1F084518DB1709C78F352EA2CA7446F3997ADA2F30DD93D0D7AB8BB513B26659CA153EAA9B88B8D55F44C277F899EB40392FC2774AF8A32E276FADFC33D4AF18F67E2EB56EC122B2D7BA75F3F6723A3C7B101BC5DD5A59641F6B5C83B2088E82F1C63C7A2B39A6340BEB8A89CD5E93C8EA16F0833CD29F7448ABF2C45F7055E1118152DF8B43B4FAE440842D136D30F5A1F201090F99727278B2FA344DBCCBB08EB32035A2D4E0E6172649EBDC3A9A7EA4C65B1538171A056E9A279A2DF32185045E61B02B475270F7653E9AEEFD258EE6CD31D269104A346E2F3A0E10987F8B4CBBDACD66E782A46F33E0EBCCBAA16802BA5055BCF7E5D4F6B3CB6079679AE0C5A2C42EBF385B7719A26341484444D25FC498FE95C066239A7E6F62E0819DBA28D686FC564BBCF7C87124215BBEFC542D0DBC78001C912CBFF6B84D42C530FC4468A40A85EA028CE953FFBE2B3F2056E5230A35594EC40C85835106B5B956B5B908B006D24ACB42737F392ABA98C4AF2059F25E9F8ED5DD5727DF0D9B3433246388B398F73FC29573CA1C963AD131C9207B8C3A5FF62C0EC84A520B63F208EB1DC71510A889EE47ACA872DC746FFA60549E0AD1701F74BD66*E1*C49BB775EA5E4EE0D29FEFD1FB3C*rdvpref
`
But when I execute the command to start hashing the file I this error 

```
./hashcat -m 15500 -a 3 -1 '?u|' -w 3 ../JKS-private-key-cracker-hashcat/hash.txt ?1?1?1?1?1?1?1?1?1
hashcat (v5.1.0-1484-gbfd95d42) starting...

OpenCL API (OpenCL 1.2 (Apr  7 2019 18:38:19)) - Platform #1 [Apple]
====================================================================
* Device #1: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz, skipped
* Device #2: Intel(R) Iris(TM) Graphics 6100, 1472/1536 MB (384 MB allocatable), 48MCU

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashfile '../JKS-private-key-cracker-hashcat/hash.txt' on line 1 ($jkspr...B775EA5E4EE0D29FEFD1FB3C*rdvpref): Token encoding exception
No hashes loaded.

Started: Wed Nov 27 19:56:55 2019
Stopped: Wed Nov 27 19:56:55 2019
```
What did I do wrong please ?

**Comment by floyd-fuh** [comment]
I didn't try it but from here it looks like you did nothing wrong, but I asked at hashcat as they seem to have changed something that might have broken the module. If you want to try, you can try an older build of hashcat, which should probably work. Let me know

**Comment by floyd-fuh** [comment]
Ok, so try older versions of hashcat or the upcoming version that has the fix in https://github.com/hashcat/hashcat/commit/9a2c4e341782e347e5b3ebb0bb81b712593aafbd included
