### ISSUE TITLE
[Question] Supporting new formats

### ISSUE THREAD

**Issue by furang** [floyd-fuh/JKS-private-key-cracker-hashcat#5]
Hello.
Wanted to know how can I add support for my custom format? When I run your program with my key I get this
```bash
$ java -jar JksPrivkPrepare.jar ~/Downloads/my_key.jks 
The public key is not in RSA, DSA or EC format, but 1.2.804.2.1.1.1.1.3.1.1.
```
I know the algorithm. Looking for java implementation.
What else do I need for it? How can I get mappings for my algorithm?

PS. Thanks for your work!

**Comment by floyd-fuh** [comment]
Exciting question! This research was some time ago, so I needed to refresh my mind as well.

It seems that "1.2.804.2.1.1.1.1.3.1.1" is:

Derzhavni STandarty Ukrainy (DSTU) 4145-2002 encryption with GOsudarstvennyy STandart (GOST) 34-311 hash (with usual byte ordering) or https://appdoc.app/artifact/org.bouncycastle/bcprov-jdk15on/1.54/org/bouncycastle/asn1/ua/UAObjectIdentifiers.html

I went "the engineer's" way of finding out how a plaintext private key looks like and just generated thousands of them for each algorithm and looked at them, you can find the [fingerprint creation here](https://github.com/floyd-fuh/JKS-private-key-cracker-hashcat/tree/master/fingerprint_creation).

After you created thousands of them for each key size, you have to extract the first 20 bytes of each key (only compare keys of the same key size). Then compare these 20 bytes. I hope what you will find out is that the first byte (index 0) of each key and bytes at index 6 to to last byte (index 19) are always the same. If this is true, you can add that fingerprint here: https://github.com/floyd-fuh/JKS-private-key-cracker-hashcat/blob/6b2b557ec81745d0b43f8466f1619ef4f2c7019d/JksPrivkPrepare/JksPrivkPrepare.java#L41 . What is more likely is that the fingerprint depends on the key size, so you will have one fingerprint per keysize. You then also need to add another "else if" case here: https://github.com/floyd-fuh/JKS-private-key-cracker-hashcat/blob/6b2b557ec81745d0b43f8466f1619ef4f2c7019d/JksPrivkPrepare/JksPrivkPrepare.java#L171 that extracts the keysize and choose the correct fingerprint depending on the key size. The nice thing is that extracting the keysize should be easy, as the corresponding public key is never encrypted in JKS, so you can just extract it.

**Comment by furang** [comment]
You're absolutely correct about algorithm. The problem is I can't find implementation in java( But it seems there are implementations for js and python.

I've read your text few times. Sounds very wonderful and hacky. But I think i need some time to digest it))

**Comment by floyd-fuh** [comment]
The algorithm should be implemented in Java in Bouncycastle https://bouncycastle.org/

But wait a second, isn't GOST a symmetric algorithm? Then we don't have a public key/private key pair but only one key. Therefore we would really need only one fingerprint for all GOST keys or alternatively we need a different method to extract the key length (should be fairly simple to derive from the encrypted version if I'm not mistaken). But now I'm even more confused, because in JKS public keys are stored in plaintext whereas private keys are stored encrypted (with the weak algorithm we are breaking in this project). I had the impression JKS didn't store symmetric keys at all. So the question is, is that symmetric key encrypted or not in the JKS?

Btw. can you supply an example JKS file?

Let me try to convince some real crypto people to have a look at this...

**Comment by furang** [comment]
Unfortunately I'm not strong at crypto so I can't tell. Need some time to investigate this.
All I know is that dsty4145 is a standard for digital signature based on elliptic curves and it uses GOST-34311 hash function under the hood.

As for now I can't supply you with an example of such jks keystore because it's used in our country's eGov applications for auth and digital signature and the only one example I have is **my** personal key with my personal data and access to **my** bank account (that was the reason of my investigation - to learn how secure it is). But I'll think how I can supply you with one.

**Comment by vixentael** [comment]
Bouncy Castle should have DSTU4145 signer implementations.

docs

https://javadoc.io/static/org.bouncycastle/bcprov-jdk15on/1.55/org/bouncycastle/crypto/signers/DSTU4145Signer.html
http://javadox.com/org.bouncycastle/bcprov-jdk15on/1.51/org/bouncycastle/jcajce/provider/asymmetric/dstu/package-summary.html


code
https://github.com/bcgit/bc-java/tree/master/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/dstu

**Comment by furang** [comment]
@vixentael Thanks Anastasia. It was useful!

**Comment by floyd-fuh** [comment]
Thanks a lot @vixentael 

Due to the political Ukrainian-Russian conflict that is currently ongoing I don't feel like contributing to this at the moment. Not because I think it is the wrong thing to do (full disclosure and breaking insecure things is a good thing), but I don't like the timing.
